### ISSUE TITLE
Define custom fallback for <plug>(TaboutBack) or <plug>(TaboutBack) 

### ISSUE THREAD

**Issue by ghillb** [abecodes/tabout.nvim#29]
For some reason <s-tab> does not reverse shift unless I define it via `vim.keymap.set("i", "<s-tab>", "<c-d>")`. 
Is there a way to define a custom fallback to `<plug>(TaboutBack)` so that `<c-d>` gets executed and not <s-tab>, if a tabout is not possible?

**Comment by abecodes** [comment]
Hi @ghillb 

If you set act_as_shift_tab to true <S-Tab> will be called, if tabout is not possible. And here you are right, if this is not set to something, nothing will happen.

I think it could make sense to default that to <c-d> if act_as_shift_tab true, and call <S-Tab> if it is false. The original idea was, that the classic reverse tab needs user implementation, since it behaves differently base on system or terminal. Thats why I would rather stick with the current approach and use whatever the user has set up.

That said, I can introduce a config for a fallback keybinding and use that if set. Then you could set <c-d> just for tabout and bind <S-Tab> for something else. It might have a use case.

As a solution I would add the info that a reverse tab keybinding is needed for it to work to the readme. I will noodle on the fallback thing a little and implement it if needed.

Does that sound reasonable, or did I miss something?

**Comment by ghillb** [comment]
> As a solution I would add the info that a reverse tab keybinding is needed for it to work to the README. I will noodle on the fallback thing a little and implement it if needed.

I already have my `<s-tab>` set to the following:
`vim.keymap.set("i", "<s-tab>", "v:lua.s_tab_binding()", { expr = true })`
```
function _G.s_tab_binding()
  if vim.fn.pumvisible() ~= 0 then
    return replace_keycodes("<C-p>")
  else
    return replace_keycodes("<plug>(TaboutBack)")
  end
end
```
How would TaboutBack now know that it should perform a `<c-d>` as fallback?
I cannot define `vim.keymap.set("i", "<s-tab>", "<c-d>")`,  because this shadows the first binding.

**Comment by abecodes** [comment]
@ghillb Thanks for pointing that out 😊
I will give it a shot at the weekend and come back to you.

**Comment by abecodes** [comment]
Hi @ghillb 

could you give the branch `feature/fallback` a shot and see if this fixes your issue? And maybe see if something broke?

The settings in the config are `default_tab` and `default_shift_tab`.

**Comment by ghillb** [comment]
Hi @abecodes, I checked out the `feature/fallback` branch, added `default_tab = '<C-t>'` &  `default_shift_tab = '<C-d>'` to the config and noticed the following.

For some reason, it now inserts `<Plug>(Tabout)` or `<plug>(TaboutBack)` every time a tabout is possible or the fallback should kick in (line 31 in screen):
![image](https://user-images.githubusercontent.com/35503959/163851801-66be4686-87f8-40aa-bd5f-26b25ab7aaaa.png)

**Comment by abecodes** [comment]
Hi @ghillb 
Can you remove your custom tab_binding and set the `tabkey` in the confing to `<TAB>` and test again, just to see if it works?

**Comment by abecodes** [comment]
Hi @ghillb ,

that sounds really strange...I don't run into this kind of issues here on my end. If you feel wild, you could comment out all other plugins and just give tabout with treesitter a shot, I am wondering what will happen...

**Comment by ghillb** [comment]
You are right, it has to be a conflict with some plugin. With a minimal config this feature works.

**Comment by abecodes** [comment]
Good to hear ;) Crossing fingers you find the issue quickly.

Thanks for your teamwork, let me know if smth else pops up ;)
