### ISSUE TITLE
[Bug] Unexpected behavior to tabout `[]` in the last line.

### ISSUE THREAD

**Issue by Fau818** [abecodes/tabout.nvim#41]
https://user-images.githubusercontent.com/75115028/215310543-1d358c45-7f48-440b-ac67-05d725688b5d.mov

Shown in the above video.

I can't tabout `[]` bracket pair in the last line.

**Comment by shamindras** [comment]
I realized that getting a similar issue to @Fau818, per the discussion I'd started [here](https://github.com/abecodes/tabout.nvim/discussions/42#discussion-4807834).

**Comment by abecodes** [comment]
Hi @Fau818 

well, it is not that unexpected, since the `[]` should not be at that place in lua...therefore treesitter does not mark it as it would a correct node and thus tabout does not work (related to @shamindras [discussion](https://github.com/abecodes/tabout.nvim/discussions/42#discussioncomment-4870452).

There is a branch to have a fallback for this, let me know if it fixes your issue

```
use({
    'abecodes/tabout.nvim',
    branch = 'feature/tabout-md',
    wants = { 'nvim-treesitter' }, -- or require if not used so far
    after = { 'nvim-cmp' }, -- if a completion plugin is using tabs load it before
  })
```

**Comment by shamindras** [comment]
Just posting a quick update here for posterity, from [the related discussion](url) with @abecodes.

In short, this is working by simply testing valid `lua` autopairs syntax, i.e. checking tabout against `()`, `{}` pairs worked for me, as opposed to `[]`, which was also interestingly @Fau818's test case 😄 .

I did not check the `tabout-md` branch, since I will like to go with the treesitter config, though I do think it would be cool to **toggle** between the 2 modes as needed. Assuming of course that having it as a toggle is not an intense maintenance chore.

In either case, thanks @abecodes for your package and help here

**Comment by Fau818** [comment]
Thank you both for your enthusiastic help! And I also checked out this [discussion](https://github.com/abecodes/tabout.nvim/discussions/42#discussioncomment-4870452).
This made me realize that `tabout` works based on `treesitter`, and made me understand why I couldn't jump out correctly.

---

But there is still one thing that needs to be addressed, it doesn't work well in `gitcommit` filetype. If I want to use tabout in the gitcommit filetype, I have to set the `ignore_beginning = true`. 
(Even if I switch to the `feature/tabout-md` branch, this still doesn't work well.)

https://user-images.githubusercontent.com/75115028/216798898-3b8aa93b-64ce-41d7-9d22-fd24111080ea.mov

But if I turn on the `ignore_beginning = true` option, there are some unexpected behaviors .

https://user-images.githubusercontent.com/75115028/216799340-08cd62bd-f935-41ce-88bc-f740a1885326.mov

---

Based on the problems I've encountered, I think it might be nice to have a way to get out of the treesitter.
For example, like [ijimiji/tabout.nvim](https://github.com/ijimiji/tabout.nvim).

In the end, I think it's beyond the scope of this issue to discuss further.
Perhaps a follow-up discussion would be better [here](https://github.com/abecodes/tabout.nvim/discussions/42#discussioncomment-4870452).

**Comment by abecodes** [comment]
Hi @Fau818,

I am not against removing treesitter...at the time of writing this plugin is was the hottest 💩 and I didn't know better 🤣 I was concerned about parsing and treesitter seemed to be abstracting that all away.

But since most of the issues are related to treesitter one way or another, maybe it would make sense to remove it completely.

@Fau818 @shamindras if anyone of you wants to prepare a PR, feel free, otherwise I will give it a shot the upcoming weekend.

Thanks for your input and reporting issues, really appreciated 😊
